HEADSETS_DEFAULT_ROOM = 'headset'
SELECTION_ROOM = 'selection'

MAX_NUM_CLIENTS_CONNECTED = 1
CLIENTS_ROOM = [SELECTION_ROOM]
MAX_NUM_HEADSETS_CONNECTED = 1
HEADSETS_ROOM = [HEADSETS_DEFAULT_ROOM, SELECTION_ROOM]
MAX_NUM_POSITION_ESTIMATORS_CONNECTED = 1
POSITION_ESTIMATORS_ROOM = []